#file: noinspection YAMLSchemaValidation,YAMLSchemaValidation

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Development settings
host: 127.0.0.1
port: 9000

author: "waki-taki"
title: "waki-taki"
faviconcolor: "#2cdad7"
keywords: "Software Engineering, Interactive Engineering"

instagram: "https://www.instagram.com/waki-taki/"
email: "contact@waki-taki.com"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
      type: post
      class: "post video-post"
