#file: noinspection YAMLSchemaValidation,YAMLSchemaValidation

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Development settings
host: 0.0.0.0
port: 9000

author: "Willy Nolan"
title: "Willy Nolan"
faviconcolor: "#2cdad7"
keywords: "Software Engineering, Interactive Engineering"

instagram: "https://www.instagram.com/computersarecool/"
email: "willy@willynolan.com"
github: "https://github.com/computersarecool"
linkedin: "https://www.linkedin.com/in/willynolan/"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
      type: post
      class: "post video-post"
